### ISSUE TITLE
Couple of unclear instructions in Construction Guide

### ISSUE THREAD

**Issue by Naeloo** [asterics/FLipMouse#19]
Hi,

a couple of proposed amendments to the construction guide:

- It would be prudent to make the user check values or text of the resistor banks before soldering them in as they're easily confused. There's a warning text "Take care of the text on these parts" but that's neither English nor does it give any hints what the text should be. A warning to the likes of "Before soldering make sure you're using the correct resistor bank with a value of x Ohms, verifiable with a Multimeter or by the text "xx" on the part"
- Maybe a warning to check the continuity / proper connection of the soldering points on the bottom of the board befopre soldering the pressure sensor because it covers those pins and you can't check afterwards which causes debugging headaches
- On the instructions for soldering the pin header on the daughterboard, nowhere does it mention that there's a little notch that should be aligned with the position of the header and on the illustration it's also not there - this is probably the most important of the points. Furthermore, the instruction "bend the pin header to a straight angle" is a bit confusing - you might mean "making it level/even with the board"? This isn't as big a problem because the image makes it pretty clear how it should look.

I understand that a lot of these issues are problems that only a non-experienced constructor might encounter, but in the spirit of keeping the project easily accessible by anyone and the otherwise very good Construction Guide, I personally think these should be fixed to prevent people making the same mistakes I have. Maybe I've just missed these things in the construction guide, in which case feel free to ignore this.

Thanks

**Comment by benjaminaigner** [comment]
Dear @Naeloo ,
we have updated the construction guide.
Thank you very much for your hints, I hope we took them properly into the new version.
Would it be possible for you to check the construction guide if you find the instructions clear?

Thank you very much for your contribution and interest in the FLipMouse project!
