### ISSUE TITLE
Unclear calibration on slot-switch if gain!=50

### ISSUE THREAD

**Issue by benjaminaigner** [asterics/FLipMouse#21]
If the sensor gain for one slot is set to 50 and for another one to != 50, calibration does not work as expected. Mostly one slot is outside deadzone, even if idle.

Problem: https://github.com/asterics/FLipMouse/blob/9b8135d0bd9076215600ded29f1fc9ff58bce8c2/FLipWare/commands.cpp#L236

@ChrisVeigl @klues 
Is there any need to have gain settings individual for each slot?

**Comment by klues** [comment]
Question: Is gain = sensitiviy or are they different? 
I don't know if different gains for different slots are needed. 

I encountered a similar issue at developing the new web GUI: After rotating the mouse (`AT RO`) there is also often a movement of the mouse, even in idle state. my workaround there is to trigger a re-calibration after each `AT RO` command. However this maybe also should be improved directly in the firmware.

**Comment by benjaminaigner** [comment]
gain = individual gain for each sensor, used BEFORE applying deadzone/sensitivity/acceleration
sensitivity = mapping from raw sensor value to mouse coordinates

gain is not widely used, anyway in my opinion gain is a value which is common for all slots of one FLipmouse.

**Comment by klues** [comment]
ok yeah, sounds like gain is not really needed for each slot separately.

**Comment by ChrisVeigl** [comment]
gain sliders removed with 787948da51110b392b2f59a2988b0b0f38849ce3
