### ISSUE TITLE
FlipMouse C# GUI - List of slots is not set correctly, if settings are not loaded from mouse

### ISSUE THREAD

**Issue by benjaminaigner** [asterics/FLipMouse#26]
See video,
if you press "no" if you get asked for loading settings from the Flipmouse, the drop down menu for available slots is empty until the buttons next/previous slot are pressed.
[video_gui_bug.zip](https://github.com/asterics/FLipMouse/files/2097858/video_gui_bug.zip)

**Comment by ChrisVeigl** [comment]
fixed with 787948da51110b392b2f59a2988b0b0f38849ce3
