### ISSUE TITLE
Inconsistent EEPROM state

### ISSUE THREAD

**Issue by benjaminaigner** [asterics/FLipMouse#31]
When programming a FLipMouse, normally there are no slots available (only the default config, not saved in EEPROM).

Using a terminal program, entering:
`"AT" --> "OK"`
`"AT LI" --> no feedback`
`"AT LA"` --> should write the default slot,but I get following incomplete feedback, error messages and a stuck FLipMouse:

```                                                                                                                                 
Initializing EEPROM!
Deleting all IR slots
Error: seperator problem0
Error: seperator problem0
Error: seperator problem95
Slot:
AT AX 40
AT AY 40
AT DX 20
AT DY 20
AT MS 50
AT AC 20
AT TS 400
AT TP 600
AT WS 3
AT SP 800
AT SS 10
AT MM 1
AT GU 50
AT GD 50
AT GL 50
AT GR 50
AT RO 0
AT BT 1
AT II 
AT BM 01
AT 
```
Current master (v2.8.3).
It is also not working with the C# GUI.

**Comment by benjaminaigner** [comment]
Also there are no beeps on start-up, initializing,...
Only if the mouse is attached, and `AT CA` is entered on the console.

**Comment by ChrisVeigl** [comment]
does this only happen when programming first time (with a new EEPROM) ?
i cannot replicate the problem - after reprogramming and also when changing version number (to reinitialize EEPRO content) AT LI and AT LA work fine...  maybe because the EEPROM already contains data...

**Comment by benjaminaigner** [comment]
Just found the problem:
In Arduino, use "Tools"->"Optimize" ->__`Smallest Code`__

do NOT use `Smallest Code with LTO`
