### ISSUE TITLE
`AT SR`: add button states

### ISSUE THREAD

**Issue by benjaminaigner** [asterics/FLipMouse#39]
I think it would be an improvement to see current button states (physical & virtual) in report raw values.
We could visualize states in the GUI and process this data otherwise.

@ChrisVeigl  Do you think it would be a problem to just add another field in the report?
E.g.: ```<pressure>,<up>,<down>,<left>,<right>,<x>,<y>,<buttons>```

Current C# GUI does not support this format, no live values are shown anymore.

**Comment by ChrisVeigl** [comment]
shouldn't be a problem to add that....
we could make a branch for that enhancement, and i'll change the c# gui accordingly.

**Comment by klues** [comment]
Yeah, this improvement would be great for the visualization i'm currently working on. @benjaminaigner sounds like you already tried to add the button states, do you have pushed it to a branch somewhere?

**Comment by benjaminaigner** [comment]
Would be here :-):
https://github.com/asterics/FLipMouse/tree/AT-SR-buttonstates
