### ISSUE TITLE
Saving config: performance and usability

### ISSUE THREAD

**Issue by klues** [asterics/FLipMouse#45]
# Usability
## Current Workflow
The current workflow for making configuration changes is:
* Open GUI
* Make changes in GUI
* Click "Test settings" in C# GUI, WebGUI automatically "tests" settings
* Click "Store settings" (C# GUI) / "Save" (Web GUI) in order to persist the configuration

## Alternative Workflow
This would be an alternative workflow:
* Open GUI
* Make changes in GUI
* Changes are applied and persisted immediately, no further user actions are required
* There are possibilities to revert the configuration to default configuration or the starting configuration of the session.

I think most of the time the user wants to keep the new configuration, so it would be a benefit for usability if no explicit action would be required for saving the config. It's also a benefit for testing if changes (e.g. sensitivity) immediately take effect and there is no need for clicking on "Test" (currently already implemented in WebGUI). 

# Technical stuff
Currently it seems to be only possible to persist a config like this:
* delete all slots with `AT DE`
* re-save all slots
* this takes about 4 seconds

# Proposed changes
* `AT SA <slotname>` should overwrite an existing slot with the current config, so a single `AT SA` command would be enough for persisting -> some milliseconds instead of 4 seconds
* I would implement WebGUI with the alternative workflow, C# GUI should stay like it is.

@ChrisVeigl, @benjaminaigner: what do you think?

**Comment by ChrisVeigl** [comment]
changing AT SA so that it overwrites the slot data in EEPROM is not trivial and would need some changes in the eeprom implementation (move all remaining data if the slot size changes), see also discussion in
https://github.com/asterics/FLipMouse/pull/46

we could discuss several strategies:
* store changed slots at the end of the list and implement a defragmentation / garbage collection
* store keystings seperately so that less data must be copied on demand
* store slot data in ESP32 flash (if BT-AddOn is available)
* use a fixed slot size (reserve memory for max keystring length) - is would be fast and easy, but is wasteful (and no option for the much smaller EEPROM in the FABI system / AVR)

**Comment by ChrisVeigl** [comment]
a first version of EEPROM slot copy is there:
https://github.com/asterics/FLipMouse/commit/8f36024bad3218f2765af4192b3722ac72003089
although it should work in theory and the EEPROM bin/block writes improve performance, this needs further consideration ...
I think it is not reasonable to save (and respectively change EEPROM content) every time a user makes small changes in the FlipMouse configuration.

**Comment by ChrisVeigl** [comment]
further worked on that, see https://github.com/asterics/FLipMouse/commit/27696be0c6627c88f11da63cb918e30bb5356a32

Using EEPROM page writes and optimized I2C buffer size, a slot save can now be performed at 1/3 of the time, and moving slots (in course of the save action) is 10 times faster.  Example timing for moving three slots and then overwriting a slot: ~580 ms.

Please note that the C# GUI in this branch now performs the AT SA action when pressing the "Test Settings" button, and that basic debug messages are turned on in the firmware.

**Comment by klues** [comment]
sounds great! 👍 
Sorry for my naive thought that `AT SA` was just lacking of a single `else` statement 😉

**Comment by benjaminaigner** [comment]
With all the last commits on v2 and the ongoing work on v3 with the RP2040 branch, we can close this issue.
