### ISSUE TITLE
openinput support

### ISSUE THREAD

**Issue by perigoso** [asterics/FLipMouse#48]
This could be a very interesting target to add to the [openinput](https://github.com/openinput-fw/openinput) project, creating this issue to check interest and show my willingness to work on support for it.

**Comment by benjaminaigner** [comment]
Dear @perigoso 

THX for showing interest in our device.

Regarding openinput support:

I see a few drawbacks with openinput on our device:
* You are not supporting AVR architecture (we share quite a codebase with the FABI device)
* There is no support for the LPC chips from the Teensy Microcontroller
* Our main objective is a highly compatible device, which should work with EVERY host supporting USB-HID

If you could clarify your vision of openinput here, it would be helpful to analyze possibilities.

Greetings

**Comment by perigoso** [comment]
Well, openinput is in very early stages, avr support is planned and lpc could be added as well.

Openinput implements a generic hid device, it will work on any host that supports hid.

We want openinput to be highly configurable firmware framework for input devices, we want to reach a point where even oem device manufacturers use our project.

The main advantage of openinput will be the protocol, a comunication layer used to control and configure the device, a cross platform control software will be implemented eventually, for now its just supported on linux with libratbagd/piper.

To clarify, it isn't yet quite ready to be the main solution for a project like this, but it could become as it matures.

**Comment by benjaminaigner** [comment]
THX for clarifying.
If it would be resource efficient enough for the Teensy LC board and the Arduino Pro Micro (ATMega32U4) we can consider it!

For now I'm closing this issue, but if you think it your project is mature enough, you're welcome to re-open this issue!

Anyway, we wish you good success with openinput!
