### ISSUE TITLE
Macros: AT MA KW \;;CR; writing "ö" instead of ";"

### ISSUE THREAD

**Issue by klues** [asterics/FLipMouse#50]
I'm testing macro function via serial console `AT MA KW \;;CR;`:
1. Writes `ö` instead of  `;`
2. Does a right-click with the mouse as expected.

**Comment by ChrisVeigl** [comment]
did you compile the FlipMouse firmware with german keyboard layout (Teensyduino Option in Arduino IDE) ?
if not,  the english keyboard layout is used and the described behaviour should be correct.

**Comment by klues** [comment]
Ah, did not know, that there is this option for keyboard layout in Arduino for Teensy. Tried again with German layout and everything works as expected 👍
